name: CI

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Check ADRs naming convention
      run: |
        set -e
        cd doc/adr/
        for file in *; do echo $file; [[ $file =~ ^.+\.md$ ]]; done

